"""
src/agents/langgraph/nodes/web_research_node.py — Web Research Agent
====================================================================
Integrates Tavily, SerpAPI, or Brave Search to fetch live web data.
Deduplicates search results by URL and appends to retrieved_docs and citations.
"""
import asyncio
import hashlib
from typing import Dict, List, Any
import httpx
from src.agents.langgraph.state import AgentState
from src.core.config import settings
from src.core.llm_factory import current_user_keys
from src.core.logger import get_logger

logger = get_logger(__name__)


async def search_tavily(query: str, api_key: str, max_results: int = 5) -> List[Dict[str, Any]]:
    url = "https://api.tavily.com/search"
    payload = {
        "api_key": api_key,
        "query": query,
        "search_depth": "smart",
        "include_answer": False,
        "max_results": max_results
    }
    async with httpx.AsyncClient() as client:
        try:
            response = await client.post(url, json=payload, timeout=15.0)
            if response.status_code == 200:
                data = response.json()
                results = []
                for item in data.get("results", []):
                    results.append({
                        "title": item.get("title", "Web Result"),
                        "url": item.get("url", ""),
                        "content": item.get("content", ""),
                    })
                return results
            else:
                logger.warning(f"[Web Research] Tavily Search API error status={response.status_code}: {response.text}")
        except Exception as e:
            logger.warning(f"[Web Research] Tavily Search API exception: {e}")
    return []


async def search_serpapi(query: str, api_key: str, max_results: int = 5) -> List[Dict[str, Any]]:
    url = "https://serpapi.com/search"
    params = {
        "q": query,
        "api_key": api_key,
        "engine": "google",
        "num": max_results
    }
    async with httpx.AsyncClient() as client:
        try:
            response = await client.get(url, params=params, timeout=15.0)
            if response.status_code == 200:
                data = response.json()
                results = []
                for item in data.get("organic_results", []):
                    results.append({
                        "title": item.get("title", "Web Result"),
                        "url": item.get("link", ""),
                        "content": item.get("snippet", ""),
                    })
                return results
            else:
                logger.warning(f"[Web Research] SerpAPI error status={response.status_code}: {response.text}")
        except Exception as e:
            logger.warning(f"[Web Research] SerpAPI exception: {e}")
    return []


async def search_brave(query: str, api_key: str, max_results: int = 5) -> List[Dict[str, Any]]:
    url = "https://api.search.brave.com/res/v1/web/search"
    headers = {
        "Accept": "application/json",
        "Accept-Encoding": "gzip",
        "X-Subscription-Token": api_key
    }
    params = {
        "q": query,
        "count": max_results
    }
    async with httpx.AsyncClient() as client:
        try:
            response = await client.get(url, headers=headers, params=params, timeout=15.0)
            if response.status_code == 200:
                data = response.json()
                results = []
                for item in data.get("web", {}).get("results", []):
                    results.append({
                        "title": item.get("title", "Web Result"),
                        "url": item.get("url", ""),
                        "content": item.get("description", ""),
                    })
                return results
            else:
                logger.warning(f"[Web Research] Brave Search API error status={response.status_code}: {response.text}")
        except Exception as e:
            logger.warning(f"[Web Research] Brave Search API exception: {e}")
    return []


async def web_research_node(state: AgentState) -> dict:
    """
    Web Research Agent — queries Tavily, SerpAPI, or Brave Search
    using the queries generated by the planner.
    Appends results to retrieved_docs and citations in state.
    """
    logger.info("[Web Research] Starting web research node")
    
    # Check if context is required. If not, skip web research.
    if not state.get("requires_context", True):
        logger.info("[Web Research] requires_context=False — skipping web research")
        return {
            "current_node": "web_researcher",
        }

    # Resolve API keys: check custom user keys, then fallback to global settings
    keys_dict = {}
    try:
        keys_dict = current_user_keys.get() or {}
    except Exception as e:
        logger.debug(f"[Web Research] Could not get current_user_keys context: {e}")
        
    tavily_key = keys_dict.get("tavily") or getattr(settings, "TAVILY_API_KEY", "")
    serpapi_key = keys_dict.get("serpapi") or getattr(settings, "SERPAPI_API_KEY", "")
    brave_key = keys_dict.get("brave") or getattr(settings, "BRAVE_API_KEY", "")

    # Choose search provider based on key availability
    search_fn = None
    api_key = ""
    provider_name = ""

    if tavily_key:
        search_fn = search_tavily
        api_key = tavily_key
        provider_name = "Tavily"
    elif serpapi_key:
        search_fn = search_serpapi
        api_key = serpapi_key
        provider_name = "SerpAPI"
    elif brave_key:
        search_fn = search_brave
        api_key = brave_key
        provider_name = "Brave Search"

    if not search_fn:
        logger.warning("[Web Research] No Web Search API Key (Tavily, SerpAPI, Brave) configured. Skipping web search.")
        return {
            "current_node": "web_researcher",
        }

    plan = state.get("plan", [])
    query = state.get("query", "")
    search_queries = plan if plan else [query]

    logger.info(f"[Web Research] Using {provider_name} to search for {len(search_queries)} queries")

    # Run searches in parallel
    tasks = [search_fn(sq, api_key, max_results=4) for sq in search_queries]
    search_results_lists = await asyncio.gather(*tasks, return_exceptions=True)

    # Accumulate results
    all_web_results = []
    seen_urls = set()
    
    # Track existing doc sources to avoid duplicate retrieval if any overlap exists
    existing_docs = state.get("retrieved_docs", []) or []
    for doc in existing_docs:
        meta = doc.get("metadata", {})
        if "url" in meta and meta["url"]:
            seen_urls.add(meta["url"])

    for res_list in search_results_lists:
        if isinstance(res_list, Exception):
            logger.error(f"[Web Research] Search task failed: {res_list}")
            continue
        for res in res_list:
            url = res.get("url", "")
            if url and url in seen_urls:
                continue
            if url:
                seen_urls.add(url)
            all_web_results.append(res)

    logger.info(f"[Web Research] Found {len(all_web_results)} new unique web search results")

    # Format web search results as documents and citations
    updated_docs = list(state.get("retrieved_docs", []) or [])
    updated_citations = list(state.get("citations", []) or [])
    
    start_index = len(updated_citations)

    for i, res in enumerate(all_web_results):
        title = res.get("title", "Web Result")
        url = res.get("url", "")
        content = res.get("content", "")
        
        # Calculate a short deterministic hash for doc_id
        doc_id = hashlib.sha1((url + content[:100]).encode()).hexdigest()[:12]
        
        doc_item = {
            "page_content": content,
            "metadata": {
                "source": title,
                "filename": title,
                "url": url,
                "page": "N/A",
                "chunk_index": "N/A",
                "total_chunks": "N/A",
                "uploaded_at": "Web Search",
            },
            "doc_id": doc_id,
        }
        
        confidence = round(max(0.95 - (start_index + i) * 0.05, 0.50), 2)
        
        citation_item = {
            "index": start_index + i + 1,
            "rank": start_index + i + 1,
            "doc_id": doc_id,
            "source": title,
            "filename": title,
            "page": "N/A",
            "url": url,
            "chunk_index": "N/A",
            "total_chunks": "N/A",
            "uploaded_at": "Web Search",
            "snippet": content[:200].strip(),
            "confidence": confidence,
        }
        
        updated_docs.append(doc_item)
        updated_citations.append(citation_item)

    logger.info(f"[Web Research] Completed: total_docs={len(updated_docs)}, total_citations={len(updated_citations)}")

    return {
        "retrieved_docs": updated_docs,
        "citations": updated_citations,
        "current_node": "web_researcher",
    }
