"""
export_service.py — PDF, DOCX, XLSX, and Markdown export builders for research reports and tasks.
"""
import io
import re
from datetime import datetime
from typing import List, Dict, Any, Optional
from src.core.logger import get_logger

logger = get_logger(__name__)


def generate_pdf_report(
    query: str,
    report_text: str,
    citations: Optional[List[Dict[str, Any]]] = None,
    company_name: str = "TriVisionX Enterprise",
    logo_url: Optional[str] = None,
    footer_text: str = "Confidential • Generated by TriVisionX AI Research Copilot",
) -> bytes:
    """Generate a formatted PDF document for research reports using ReportLab (with fallback)."""
    citations = citations or []
    ts = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.lib import colors
        from reportlab.platypus import (
            SimpleDocTemplate,
            Paragraph,
            Spacer,
            HRFlowable,
            Table,
            TableStyle,
        )
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.enums import TA_CENTER, TA_LEFT

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=40,
            leftMargin=40,
            topMargin=40,
            bottomMargin=40,
        )

        styles = getSampleStyleSheet()

        # Custom Styles
        company_style = ParagraphStyle(
            "CompanyHeader",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=10,
            leading=12,
            textColor=colors.HexColor("#4F46E5"),
            textTransform="uppercase",
        )
        title_style = ParagraphStyle(
            "ReportTitle",
            parent=styles["Title"],
            fontName="Helvetica-Bold",
            fontSize=22,
            leading=26,
            textColor=colors.HexColor("#111827"),
            alignment=TA_LEFT,
        )
        meta_style = ParagraphStyle(
            "MetaText",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9,
            leading=13,
            textColor=colors.HexColor("#6B7280"),
        )
        h2_style = ParagraphStyle(
            "SectionH2",
            parent=styles["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=14,
            leading=18,
            textColor=colors.HexColor("#1F2937"),
            spaceBefore=14,
            spaceAfter=6,
        )
        body_style = ParagraphStyle(
            "ReportBody",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=10,
            leading=15,
            textColor=colors.HexColor("#374151"),
            spaceAfter=8,
        )
        citation_style = ParagraphStyle(
            "CitationText",
            parent=styles["Normal"],
            fontName="Helvetica-Oblique",
            fontSize=9,
            leading=13,
            textColor=colors.HexColor("#4B5563"),
        )

        story = []

        # Company Header & Date
        story.append(Paragraph(company_name.upper(), company_style))
        story.append(Spacer(1, 4))
        story.append(Paragraph(f"AI Research Report — {ts}", meta_style))
        story.append(Spacer(1, 10))

        # Title / Query
        clean_query = query.strip() or "Research Summary"
        story.append(Paragraph(f"Query: {clean_query}", title_style))
        story.append(Spacer(1, 10))
        story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#E5E7EB"), spaceAfter=15))

        # Process Markdown-like text into PDF Flowables
        lines = report_text.split("\n")
        for line in lines:
            line_str = line.strip()
            if not line_str:
                story.append(Spacer(1, 6))
                continue
            if line_str.startswith("# "):
                story.append(Paragraph(line_str.replace("# ", ""), title_style))
                story.append(Spacer(1, 6))
            elif line_str.startswith("## "):
                story.append(Paragraph(line_str.replace("## ", ""), h2_style))
                story.append(Spacer(1, 4))
            elif line_str.startswith("### "):
                story.append(Paragraph(line_str.replace("### ", ""), h2_style))
                story.append(Spacer(1, 4))
            elif line_str.startswith("- ") or line_str.startswith("* "):
                bullet_text = line_str[2:].replace("**", "<b>").replace("**", "</b>")
                story.append(Paragraph(f"• {bullet_text}", body_style))
            else:
                formatted_line = line_str.replace("**", "<b>").replace("**", "</b>")
                story.append(Paragraph(formatted_line, body_style))

        # Citations Section
        if citations:
            story.append(Spacer(1, 15))
            story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#E5E7EB"), spaceAfter=10))
            story.append(Paragraph("References & Citations", h2_style))
            for cit in citations:
                source = cit.get("filename") or cit.get("source") or "Document Source"
                page = cit.get("page", "")
                snippet = cit.get("snippet", "")
                page_str = f" (Page {page})" if page and page != "N/A" else ""
                cit_line = f"<b>• {source}{page_str}</b>"
                if snippet:
                    cit_line += f"<br/><i>\"{snippet[:120]}...\"</i>"
                story.append(Paragraph(cit_line, citation_style))
                story.append(Spacer(1, 4))

        # Footer space
        story.append(Spacer(1, 20))
        story.append(Paragraph(footer_text, meta_style))

        doc.build(story)
        return buffer.getvalue()

    except ImportError:
        logger.warning("ReportLab not installed. Falling back to plain PDF formatting.")
        pdf_content = (
            f"%PDF-1.4\n1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n"
            f"2 0 obj<</Type/Pages/Count 1/Kids[3 0 R]>>endobj\n"
            f"3 0 obj<</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R/Resources<<>>>>endobj\n"
            f"xref\n0 4\n0000000000 65535 f\n0000000009 00000 n\n0000000052 00000 n\n0000000101 00000 n\n"
            f"trailer<</Size 4/Root 1 0 R>>\nstartxref\n178\n%%EOF"
        )
        return pdf_content.encode("utf-8")


def generate_docx_report(
    query: str,
    report_text: str,
    citations: Optional[List[Dict[str, Any]]] = None,
    company_name: str = "TriVisionX Enterprise",
    footer_text: str = "Confidential • Generated by TriVisionX AI Research Copilot",
) -> bytes:
    """Generate a Microsoft Word (.docx) document for research reports using python-docx."""
    citations = citations or []
    ts = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    try:
        import docx
        from docx.shared import Pt, RGBColor, Inches
        from docx.enum.text import WD_ALIGN_PARAGRAPH

        doc = docx.Document()

        # Set page margins
        for section in doc.sections:
            section.top_margin = Inches(0.8)
            section.bottom_margin = Inches(0.8)
            section.left_margin = Inches(0.8)
            section.right_margin = Inches(0.8)

        # Company Header
        p_comp = doc.add_paragraph()
        run_comp = p_comp.add_run(company_name.upper())
        run_comp.font.name = "Arial"
        run_comp.font.size = Pt(9)
        run_comp.font.bold = True
        run_comp.font.color.rgb = RGBColor(79, 70, 229) # Indigo

        p_meta = doc.add_paragraph()
        run_meta = p_meta.add_run(f"AI Research Report • Generated {ts}")
        run_meta.font.name = "Arial"
        run_meta.font.size = Pt(8.5)
        run_meta.font.color.rgb = RGBColor(107, 114, 128)

        # Query Title
        h1 = doc.add_heading(level=1)
        run_h1 = h1.add_run(f"Research Query: {query}")
        run_h1.font.name = "Arial"
        run_h1.font.size = Pt(18)
        run_h1.font.bold = True
        run_h1.font.color.rgb = RGBColor(17, 24, 39)

        doc.add_paragraph("─" * 55)

        # Body Text
        lines = report_text.split("\n")
        for line in lines:
            line_str = line.strip()
            if not line_str:
                continue
            if line_str.startswith("# "):
                doc.add_heading(line_str.replace("# ", ""), level=1)
            elif line_str.startswith("## "):
                doc.add_heading(line_str.replace("## ", ""), level=2)
            elif line_str.startswith("### "):
                doc.add_heading(line_str.replace("### ", ""), level=3)
            elif line_str.startswith("- ") or line_str.startswith("* "):
                p = doc.add_paragraph(style="List Bullet")
                p.add_run(line_str[2:].replace("**", ""))
            else:
                p = doc.add_paragraph()
                p.add_run(line_str.replace("**", ""))

        # Citations Section
        if citations:
            doc.add_heading("References & Citations", level=2)
            for cit in citations:
                source = cit.get("filename") or cit.get("source") or "Document Source"
                page = cit.get("page", "")
                snippet = cit.get("snippet", "")
                page_str = f" (p. {page})" if page and page != "N/A" else ""
                
                p_cit = doc.add_paragraph(style="List Bullet")
                r_cit = p_cit.add_run(f"{source}{page_str}")
                r_cit.bold = True
                if snippet:
                    p_snip = doc.add_paragraph()
                    r_snip = p_snip.add_run(f"\"{snippet[:150]}\"")
                    r_snip.italic = True
                    r_snip.font.size = Pt(9)
                    r_snip.font.color.rgb = RGBColor(107, 114, 128)

        # Footer Text
        p_foot = doc.add_paragraph()
        p_foot.alignment = WD_ALIGN_PARAGRAPH.CENTER
        r_foot = p_foot.add_run(f"\n{footer_text}")
        r_foot.font.name = "Arial"
        r_foot.font.size = Pt(8)
        r_foot.font.color.rgb = RGBColor(156, 163, 175)

        buffer = io.BytesIO()
        doc.save(buffer)
        return buffer.getvalue()

    except ImportError:
        logger.warning("python-docx not installed. Returning text payload.")
        raw_docx = f"# {company_name}\nQuery: {query}\n\n{report_text}"
        return raw_docx.encode("utf-8")


def generate_xlsx_report(
    query: str,
    report_text: str,
    citations: Optional[List[Dict[str, Any]]] = None,
    tasks: Optional[List[Dict[str, Any]]] = None,
) -> bytes:
    """Generate an Excel (.xlsx) workbook containing structured findings, citations, and tasks."""
    citations = citations or []
    tasks = tasks or []
    ts = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    try:
        import openpyxl
        from openpyxl.styles import Font, PatternFill, Alignment, Border, Side

        wb = openpyxl.Workbook()
        
        # Sheet 1: Executive Summary
        ws1 = wb.active
        ws1.title = "Summary"
        
        header_fill = PatternFill(start_color="4F46E5", end_color="4F46E5", fill_type="solid")
        header_font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
        
        ws1["A1"] = "TriVisionX AI Research Summary"
        ws1["A1"].font = Font(name="Calibri", size=16, bold=True, color="4F46E5")
        
        ws1["A3"] = "Query:"
        ws1["B3"] = query
        ws1["A4"] = "Generated At:"
        ws1["B4"] = ts
        
        ws1["A6"] = "Section"
        ws1["B6"] = "Content"
        ws1["A6"].fill = header_fill
        ws1["A6"].font = header_font
        ws1["B6"].fill = header_fill
        ws1["B6"].font = header_font
        
        lines = [l.strip() for l in report_text.split("\n") if l.strip()]
        row_idx = 7
        for line in lines:
            if line.startswith("#"):
                ws1.cell(row=row_idx, column=1, value="Heading")
                ws1.cell(row=row_idx, column=2, value=line.replace("#", "").strip())
                ws1.cell(row=row_idx, column=1).font = Font(bold=True)
            else:
                ws1.cell(row=row_idx, column=1, value="Key Point")
                ws1.cell(row=row_idx, column=2, value=line.replace("**", ""))
            row_idx += 1

        ws1.column_dimensions["A"].width = 15
        ws1.column_dimensions["B"].width = 80

        # Sheet 2: Citations & Sources
        if citations:
            ws2 = wb.create_sheet(title="Citations")
            headers = ["#", "Source / Document", "Page", "Snippet"]
            for col_num, h_text in enumerate(headers, 1):
                cell = ws2.cell(row=1, column=col_num, value=h_text)
                cell.fill = header_fill
                cell.font = header_font

            for idx, cit in enumerate(citations, 1):
                ws2.cell(row=idx + 1, column=1, value=idx)
                ws2.cell(row=idx + 1, column=2, value=cit.get("filename") or cit.get("source") or "N/A")
                ws2.cell(row=idx + 1, column=3, value=cit.get("page") or "N/A")
                ws2.cell(row=idx + 1, column=4, value=cit.get("snippet") or "")

            ws2.column_dimensions["A"].width = 6
            ws2.column_dimensions["B"].width = 30
            ws2.column_dimensions["C"].width = 10
            ws2.column_dimensions["D"].width = 60

        # Sheet 3: Tasks Export (if tasks passed)
        if tasks:
            ws3 = wb.create_sheet(title="Tasks")
            task_headers = ["ID/Code", "Title", "Type", "Status", "Priority", "Progress", "Assignee", "Due Date"]
            for col_num, h_text in enumerate(task_headers, 1):
                cell = ws3.cell(row=1, column=col_num, value=h_text)
                cell.fill = header_fill
                cell.font = header_font

            for idx, task in enumerate(tasks, 1):
                ws3.cell(row=idx + 1, column=1, value=task.get("code") or task.get("id") or f"TASK-{idx}")
                ws3.cell(row=idx + 1, column=2, value=task.get("title") or "")
                ws3.cell(row=idx + 1, column=3, value=task.get("type") or "Task")
                ws3.cell(row=idx + 1, column=4, value=task.get("status") or "todo")
                ws3.cell(row=idx + 1, column=5, value=task.get("priority") or "medium")
                ws3.cell(row=idx + 1, column=6, value=f"{task.get('progress', 0)}%")
                
                assignee = task.get("assignee", {})
                assignee_name = assignee.get("name") if isinstance(assignee, dict) else str(assignee)
                ws3.cell(row=idx + 1, column=7, value=assignee_name or "Unassigned")
                ws3.cell(row=idx + 1, column=8, value=task.get("dueDate") or "N/A")

            ws3.column_dimensions["A"].width = 12
            ws3.column_dimensions["B"].width = 35
            ws3.column_dimensions["C"].width = 15
            ws3.column_dimensions["D"].width = 12
            ws3.column_dimensions["E"].width = 12
            ws3.column_dimensions["F"].width = 10
            ws3.column_dimensions["G"].width = 20
            ws3.column_dimensions["H"].width = 15

        buffer = io.BytesIO()
        wb.save(buffer)
        return buffer.getvalue()

    except ImportError:
        logger.warning("openpyxl not installed. Returning CSV content.")
        csv_lines = [f"Query,{query}", f"Generated,{ts}", "", "Key Points:"]
        for line in report_text.split("\n"):
            if line.strip():
                clean_line = line.replace('"', '""').strip()
                csv_lines.append(f'"{clean_line}"')
        return "\n".join(csv_lines).encode("utf-8")
