"""
third_party_integrations.py — Slack/Teams Webhooks, Notion, Confluence, and Jira API integrations.
"""
import base64
import json
import httpx
from typing import Dict, Any, List, Optional
from core.logger import get_logger

logger = get_logger(__name__)


async def send_slack_webhook(
    webhook_url: str,
    query: str,
    summary: str,
    citations_count: int = 0,
    channel_name: str = "#research-reports",
) -> Dict[str, Any]:
    """Push formatted research summary to a Slack channel via Incoming Webhook."""
    if not webhook_url:
        return {"success": False, "error": "Slack Webhook URL is not configured"}

    clean_summary = summary[:500] + "..." if len(summary) > 500 else summary

    payload = {
        "text": f"🧠 *New AI Research Report*: {query}",
        "blocks": [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": "📊 TriVisionX AI Research Summary",
                    "emoji": True,
                },
            },
            {
                "type": "section",
                "fields": [
                    {"type": "mrkdwn", "text": f"*Topic / Query:*\n{query}"},
                    {"type": "mrkdwn", "text": f"*Citations Found:*\n{citations_count} sources"},
                ],
            },
            {"type": "divider"},
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*Executive Summary:*\n>{clean_summary}",
                },
            },
            {
                "type": "context",
                "elements": [
                    {
                        "type": "mrkdwn",
                        "text": "⚡ *Generated by TriVisionX AI Agent* • Confidential",
                    }
                ],
            },
        ],
    }

    async with httpx.AsyncClient(timeout=10.0) as client:
        res = await client.post(webhook_url, json=payload)
        if res.status_code == 200:
            return {"success": True, "message": "Successfully posted to Slack!"}
        return {"success": False, "error": f"Slack API Error ({res.status_code}): {res.text}"}


async def send_teams_webhook(
    webhook_url: str,
    query: str,
    summary: str,
    citations_count: int = 0,
) -> Dict[str, Any]:
    """Push formatted Adaptive Card to Microsoft Teams via Incoming Webhook."""
    if not webhook_url:
        return {"success": False, "error": "Teams Webhook URL is not configured"}

    clean_summary = summary[:500] + "..." if len(summary) > 500 else summary

    payload = {
        "@type": "MessageCard",
        "@context": "http://schema.org/extensions",
        "themeColor": "4F46E5",
        "summary": f"AI Research Report: {query}",
        "sections": [
            {
                "activityTitle": "📊 TriVisionX AI Research Report",
                "activitySubtitle": f"Query: {query}",
                "activityImage": "https://img.icons8.com/color/96/brain--v1.png",
                "facts": [
                    {"name": "Topic", "value": query},
                    {"name": "Citations", "value": str(citations_count)},
                    {"name": "Platform", "value": "TriVisionX AI Copilot"},
                ],
                "markdown": True,
            },
            {
                "title": "Executive Summary",
                "text": clean_summary,
            },
        ],
    }

    async with httpx.AsyncClient(timeout=10.0) as client:
        res = await client.post(webhook_url, json=payload)
        if res.status_code in (200, 202):
            return {"success": True, "message": "Successfully posted to MS Teams!"}
        return {"success": False, "error": f"Teams API Error ({res.status_code}): {res.text}"}


async def publish_to_notion(
    api_key: str,
    parent_page_id: str,
    query: str,
    report_text: str,
    citations: Optional[List[Dict[str, Any]]] = None,
    database_id: Optional[str] = None,
) -> Dict[str, Any]:
    """Publish research report as a new page in Notion using Notion API."""
    if not api_key:
        return {"success": False, "error": "Notion API Key is required"}

    citations = citations or []
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
        "Notion-Version": "2022-06-28",
    }

    # Prepare paragraph blocks
    blocks = []
    lines = [l.strip() for l in report_text.split("\n") if l.strip()]
    for line in lines[:20]: # Limit to first 20 blocks for payload limits
        if line.startswith("## "):
            blocks.append({
                "object": "block",
                "type": "heading_2",
                "heading_2": {"rich_text": [{"type": "text", "text": {"content": line.replace("## ", "")}}]}
            })
        elif line.startswith("- ") or line.startswith("* "):
            blocks.append({
                "object": "block",
                "type": "bulleted_list_item",
                "bulleted_list_item": {"rich_text": [{"type": "text", "text": {"content": line[2:]}}]}
            })
        else:
            blocks.append({
                "object": "block",
                "type": "paragraph",
                "paragraph": {"rich_text": [{"type": "text", "text": {"content": line.replace("**", "")}}]}
            })

    if citations:
        blocks.append({
            "object": "block",
            "type": "heading_2",
            "heading_2": {"rich_text": [{"type": "text", "text": {"content": "Sources & Citations"}}]}
        })
        for cit in citations:
            source_name = cit.get("filename") or cit.get("source") or "Citation"
            page = cit.get("page", "")
            page_str = f" (Page {page})" if page and page != "N/A" else ""
            blocks.append({
                "object": "block",
                "type": "bulleted_list_item",
                "bulleted_list_item": {"rich_text": [{"type": "text", "text": {"content": f"{source_name}{page_str}"}}]}
            })

    parent_payload = {}
    if database_id:
        parent_payload = {"database_id": database_id}
    elif parent_page_id:
        parent_payload = {"page_id": parent_page_id}
    else:
        return {"success": False, "error": "Either Notion Parent Page ID or Database ID is required"}

    payload = {
        "parent": parent_payload,
        "properties": {
            "title": {
                "title": [{"type": "text", "text": {"content": f"Research: {query[:80]}"}}]
            }
        },
        "children": blocks,
    }

    async with httpx.AsyncClient(timeout=12.0) as client:
        res = await client.post("https://api.notion.com/v1/pages", headers=headers, json=payload)
        if res.status_code in (200, 201):
            data = res.json()
            page_url = data.get("url", "https://notion.so")
            return {"success": True, "message": "Published to Notion!", "url": page_url}
        return {"success": False, "error": f"Notion Error ({res.status_code}): {res.text}"}


async def publish_to_confluence(
    domain: str,
    email: str,
    api_token: str,
    space_key: str,
    query: str,
    report_text: str,
    citations: Optional[List[Dict[str, Any]]] = None,
) -> Dict[str, Any]:
    """Publish research report as a page in Atlassian Confluence Cloud."""
    if not domain or not email or not api_token or not space_key:
        return {"success": False, "error": "Confluence credentials (domain, email, apiToken, spaceKey) are required"}

    citations = citations or []
    domain_clean = domain.replace("https://", "").replace("http://", "").rstrip("/")
    auth_str = base64.b64encode(f"{email}:{api_token}".encode("utf-8")).decode("utf-8")
    headers = {
        "Authorization": f"Basic {auth_str}",
        "Content-Type": "application/json",
    }

    # Build Confluence XHTML Storage Format
    html_body = f"<h2>Research Query: {query}</h2>"
    lines = [l.strip() for l in report_text.split("\n") if l.strip()]
    for line in lines:
        if line.startswith("## "):
            html_body += f"<h3>{line.replace('## ', '')}</h3>"
        elif line.startswith("- ") or line.startswith("* "):
            html_body += f"<li>{line[2:]}</li>"
        else:
            html_body += f"<p>{line.replace('**', '<strong>').replace('**', 'Setting')} </p>"

    if citations:
        html_body += "<h3>References &amp; Citations</h3><ul>"
        for cit in citations:
            src = cit.get("filename") or cit.get("source") or "Document"
            html_body += f"<li>{src}</li>"
        html_body += "</ul>"

    payload = {
        "type": "page",
        "title": f"AI Report: {query[:60]} ({datetime.utcnow().strftime('%Y-%m-%d')})",
        "space": {"key": space_key},
        "body": {
            "storage": {
                "value": html_body,
                "representation": "storage"
            }
        }
    }

    url = f"https://{domain_clean}/wiki/rest/api/content"
    async with httpx.AsyncClient(timeout=12.0) as client:
        res = await client.post(url, headers=headers, json=payload)
        if res.status_code in (200, 201):
            data = res.json()
            web_link = data.get("_links", {}).get("base", "") + data.get("_links", {}).get("webui", "")
            return {"success": True, "message": "Published to Confluence!", "url": web_link}
        return {"success": False, "error": f"Confluence API Error ({res.status_code}): {res.text}"}


async def create_jira_issue(
    domain: str,
    email: str,
    api_token: str,
    project_key: str,
    summary: str,
    description: str,
    issue_type: str = "Task",
    priority: str = "Medium",
) -> Dict[str, Any]:
    """Create an issue/ticket in Jira Cloud using Jira REST API v3."""
    if not domain or not email or not api_token or not project_key:
        return {"success": False, "error": "Jira settings (domain, email, apiToken, projectKey) are required"}

    domain_clean = domain.replace("https://", "").replace("http://", "").rstrip("/")
    auth_str = base64.b64encode(f"{email}:{api_token}".encode("utf-8")).decode("utf-8")
    headers = {
        "Authorization": f"Basic {auth_str}",
        "Content-Type": "application/json",
        "Accept": "application/json",
    }

    # Jira ADF (Atlassian Document Format) for description
    adf_description = {
        "version": 1,
        "type": "doc",
        "content": [
            {
                "type": "paragraph",
                "content": [
                    {
                        "type": "text",
                        "text": description[:1000] if description else "Generated from TriVisionX AI Task Board",
                    }
                ],
            }
        ],
    }

    payload = {
        "fields": {
            "project": {"key": project_key},
            "summary": summary[:255],
            "description": adf_description,
            "issuetype": {"name": issue_type or "Task"},
        }
    }

    url = f"https://{domain_clean}/rest/api/3/issue"
    async with httpx.AsyncClient(timeout=12.0) as client:
        res = await client.post(url, headers=headers, json=payload)
        if res.status_code in (200, 201):
            data = res.json()
            issue_key = data.get("key", "JIRA-ITEM")
            issue_url = f"https://{domain_clean}/browse/{issue_key}"
            return {"success": True, "issue_key": issue_key, "url": issue_url, "message": f"Created Jira ticket {issue_key}!"}
        return {"success": False, "error": f"Jira API Error ({res.status_code}): {res.text}"}
